//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peleg.CalculatePnrNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class global
    {
        public string name { get; set; }
        public string grp { get; set; }
        public Nullable<decimal> n_value { get; set; }
        public string c_value { get; set; }
        public Nullable<System.DateTime> d_value { get; set; }
        public string comment { get; set; }
        public string comment_local { get; set; }
        public string upd_clerk { get; set; }
        public System.DateTime upd_date { get; set; }
        public bool is_public { get; set; }
    }
}
