//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peleg.CalculatePnrNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCK_Package
    {
        public int PCK_ID { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string name_local { get; set; }
        public string Room_Type_bas { get; set; }
        public string Room_Code_bas { get; set; }
        public string cc { get; set; }
        public string dest_from { get; set; }
        public string destination_1 { get; set; }
        public string destination_2 { get; set; }
        public short flt_duration { get; set; }
        public Nullable<short> flt_duration_to { get; set; }
        public short minimum_px { get; set; }
        public short mixed_airline_only { get; set; }
        public short mixed_regular_only { get; set; }
        public short rq_flt { get; set; }
        public short rq_la { get; set; }
        public short price_flt_only { get; set; }
        public string status { get; set; }
        public Nullable<int> reference { get; set; }
        public string supplier { get; set; }
        public string service { get; set; }
        public Nullable<int> subj_id { get; set; }
        public string ext_code { get; set; }
        public bool IsHotel { get; set; }
        public bool IsCar { get; set; }
        public bool IsTranslateCC { get; set; }
        public bool IsInternetView { get; set; }
        public bool IsDesktopView { get; set; }
        public bool IsRestrictActive { get; set; }
        public bool IsMainInGroup { get; set; }
        public bool IsOverNight { get; set; }
        public bool IsNetto { get; set; }
        public Nullable<System.DateTime> LastMinutes { get; set; }
        public Nullable<byte> WeekDays { get; set; }
        public Nullable<decimal> comission { get; set; }
        public string category { get; set; }
        public string lang { get; set; }
        public string pckClass { get; set; }
        public Nullable<decimal> exchangeRate { get; set; }
        public Nullable<int> itin_id { get; set; }
        public Nullable<int> TourQuotId { get; set; }
        public Nullable<int> feedback_id { get; set; }
        public bool isBClientOnly { get; set; }
        public Nullable<int> price_id { get; set; }
        public System.DateTime dateUpd { get; set; }
        public string usr { get; set; }
    }
}
