//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peleg.CalculatePnrNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PNR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PNR()
        {
            this.Pnr_La = new HashSet<Pnr_La>();
            this.Pnr_rate = new HashSet<Pnr_rate>();
        }
    
        public int pnr_Pnr { get; set; }
        public string cmp_Code { get; set; }
        public string pnr_Agent { get; set; }
        public string pnr_branch { get; set; }
        public string pnr_Agency { get; set; }
        public string pnr_Docket { get; set; }
        public string pnr_Status { get; set; }
        public Nullable<int> pnr_Delete { get; set; }
        public System.DateTime pnr_Create_Date { get; set; }
        public string pnr_Code_Oper { get; set; }
        public string pnr_Calc_Status { get; set; }
        public Nullable<int> pnr_Internet { get; set; }
        public string pnr_External_Agent { get; set; }
        public string pnr_External_Referens { get; set; }
        public Nullable<int> pnr_Package { get; set; }
        public Nullable<int> pnr_Group_ID { get; set; }
        public string pnr_Group_Place { get; set; }
        public string pnr_GroupName { get; set; }
        public Nullable<System.DateTime> pnr_Depart_Date { get; set; }
        public string Pnr_Destination { get; set; }
        public Nullable<System.DateTime> Pnr_Arrival_Date { get; set; }
        public Nullable<short> Pnr_Flt { get; set; }
        public Nullable<short> Pnr_Htl { get; set; }
        public Nullable<short> Pnr_Car { get; set; }
        public Nullable<short> Pnr_Free { get; set; }
        public System.DateTime pnr_DateUpd { get; set; }
        public string pnr_User { get; set; }
        public string pnr_ServStatus { get; set; }
        public string pnr_BClient { get; set; }
        public string pnr_Point_of_sale { get; set; }
        public Nullable<bool> ATC { get; set; }
        public string Atribute { get; set; }
        public string PrivateMail { get; set; }
        public string Refrral { get; set; }
        public Nullable<bool> Tourist { get; set; }
        public string PNR_Docs { get; set; }
        public Nullable<System.DateTime> Pnr_Date_Locked { get; set; }
        public Nullable<short> ForWebService { get; set; }
        public string pnr_Dest_Profit { get; set; }
        public Nullable<int> smnr_id { get; set; }
        public Nullable<int> course_id { get; set; }
        public string Cancel_Reference { get; set; }
        public string Internet_Reference { get; set; }
        public Nullable<System.DateTime> Pck_FirstDate { get; set; }
        public string ESource { get; set; }
        public Nullable<int> employer_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pnr_La> Pnr_La { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pnr_rate> Pnr_rate { get; set; }
    }
}
