//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peleg.CalculatePnrNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pnr_La
    {
        public int pnr_Pnr { get; set; }
        public int LA_ID { get; set; }
        public short pla_line { get; set; }
        public string La_Supplier { get; set; }
        public string pla_Room_class_RQ { get; set; }
        public string pla_Room_class_RCV { get; set; }
        public string pla_Room_type { get; set; }
        public System.DateTime pla_Date_from { get; set; }
        public System.DateTime pla_Date_To { get; set; }
        public Nullable<int> pla_cots { get; set; }
        public Nullable<int> pla_ExtraBad { get; set; }
        public string pla_Meals { get; set; }
        public short pla_Room_Amount { get; set; }
        public string pla_Status { get; set; }
        public string pla_Remark { get; set; }
        public string pla_RefNumber { get; set; }
        public string pla_RefClerk { get; set; }
        public Nullable<byte> pla_LinkFrom { get; set; }
        public Nullable<int> msg_id { get; set; }
        public Nullable<int> pck_id { get; set; }
        public Nullable<int> pla_Pointer { get; set; }
        public string Pla_Voucher { get; set; }
        public string Pla_Voucher_Clerk { get; set; }
        public Nullable<System.DateTime> Pla_Voucher_Date { get; set; }
        public Nullable<System.DateTime> pla_DateUpd { get; set; }
        public string pla_User { get; set; }
        public string GNR_Description { get; set; }
        public string Meal_Description { get; set; }
        public string Category { get; set; }
        public string pla_Voucher_Remark { get; set; }
        public string Esource { get; set; }
    
        public virtual PNR PNR { get; set; }
    }
}
