//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peleg.CalculatePnrNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pnr_Px
    {
        public string PX_ID { get; set; }
        public int FL_ID { get; set; }
        public string flt_Combine { get; set; }
        public string pfp_Type { get; set; }
        public int pnr_Pnr { get; set; }
        public string pnr_agent { get; set; }
        public string pfp_class { get; set; }
        public Nullable<int> pfp_Return_id { get; set; }
        public string pfp_Return_Combine { get; set; }
        public string pfp_Return_class { get; set; }
        public string pfp_Return_Type { get; set; }
        public string pfp_Ticket_Number { get; set; }
        public Nullable<System.DateTime> pfp_Ticket_Date { get; set; }
        public string pfp_Ticket_Print_Oper { get; set; }
        public string pfp_status { get; set; }
        public Nullable<byte> pfp_TOD { get; set; }
        public string pfp_LOC { get; set; }
        public Nullable<byte> pfp_Priority { get; set; }
        public Nullable<bool> pfp_No_Show { get; set; }
        public Nullable<int> PCK_ID { get; set; }
        public System.DateTime pfp_DateUpd { get; set; }
        public string pfp_User { get; set; }
        public string ESource { get; set; }
    
        public virtual PNR PNR { get; set; }
    }
}
