//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peleg.CalculatePnrNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pnr_rate
    {
        public int Pnr_pnr { get; set; }
        public string PX_ID { get; set; }
        public int Pnrr_Id { get; set; }
        public string Pnrr_Supp { get; set; }
        public string Pnrr_service { get; set; }
        public string Pnrr_Flight { get; set; }
        public short Pnrr_Line { get; set; }
        public string Pnrr_Rate_Type { get; set; }
        public short Pnrr_Rate_Code { get; set; }
        public short Pnrr_Rate_PLG { get; set; }
        public int Pnrr_PriceList { get; set; }
        public string Pnrr_CurrBrutto { get; set; }
        public string Pnrr_CurrNeto { get; set; }
        public decimal Pnrr_Rate_brutto { get; set; }
        public decimal Pnrr_Rate_neto { get; set; }
        public string Pnrr_Rate_Detail { get; set; }
        public Nullable<bool> Pnrr_Price_Include { get; set; }
        public decimal Pnrr_vat { get; set; }
        public Nullable<decimal> Pnrr_Invoice { get; set; }
        public string Pnrr_Inv_Supplier { get; set; }
        public string Pnrr_Comm_Group { get; set; }
        public Nullable<decimal> Pnrr_Comm_Percent { get; set; }
        public Nullable<decimal> Pnrr_Comm_Summ { get; set; }
        public string Pnrr_Comm_Need { get; set; }
        public string Pnrr_Comm_Product { get; set; }
        public string Pnrr_Price_Type { get; set; }
        public string Pnrr_CalcStatus { get; set; }
        public Nullable<decimal> Pnrr_Client_Price { get; set; }
        public System.DateTime Pnrr_DateUpd { get; set; }
        public string Pnrr_User { get; set; }
        public Nullable<bool> ATC { get; set; }
        public Nullable<decimal> VAT_Cms { get; set; }
        public Nullable<decimal> VAT_Purch { get; set; }
        public Nullable<bool> Without_Vat { get; set; }
    
        public virtual PNR PNR { get; set; }
    }
}
