//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peleg.CalculatePnrNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PNR_Link_Supplier
    {
        public int pnr_pnr { get; set; }
        public short pla_line { get; set; }
        public string la_supplier { get; set; }
        public string rate_supplier { get; set; }
        public string lnk_User { get; set; }
        public System.DateTime lnk_DateUpd { get; set; }
    }
}
