//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peleg.CalculatePnrNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pnr_Free
    {
        public int Pnr_Pnr { get; set; }
        public short Line { get; set; }
        public string Department { get; set; }
        public Nullable<bool> FromInternet { get; set; }
        public string Service { get; set; }
        public string Type { get; set; }
        public string Supplier { get; set; }
        public string Supplier_Paid { get; set; }
        public string Confirm_By { get; set; }
        public string Referens { get; set; }
        public string Reference2 { get; set; }
        public string BasisFare { get; set; }
        public Nullable<System.DateTime> DateLimit { get; set; }
        public string CancelPRC { get; set; }
        public string FDest { get; set; }
        public string FDest_Name { get; set; }
        public System.DateTime FDate { get; set; }
        public string FHour { get; set; }
        public string TDest { get; set; }
        public string TDest_Name { get; set; }
        public Nullable<System.DateTime> Tdate { get; set; }
        public string THour { get; set; }
        public short PAX { get; set; }
        public string Status { get; set; }
        public string cc { get; set; }
        public string Remark { get; set; }
        public string Voucher_Remark { get; set; }
        public Nullable<int> Voucher_Number { get; set; }
        public Nullable<byte> Flt_Open { get; set; }
        public string Flt_Carrier { get; set; }
        public string Flt_CrrNum { get; set; }
        public string Flt_FAirp { get; set; }
        public string Flt_FAirp_Name { get; set; }
        public string Flt_FromTerminal { get; set; }
        public string Flt_TAirp { get; set; }
        public string Flt_TAirp_Name { get; set; }
        public string Flt_ToTerminal { get; set; }
        public string Flt_Class { get; set; }
        public string Car_Type { get; set; }
        public string Car_Type_Name { get; set; }
        public Nullable<int> Car_Rent_Company { get; set; }
        public Nullable<short> Car_Acount { get; set; }
        public string Car_PickUp_Station { get; set; }
        public string Car_Drop_Station { get; set; }
        public string Htl_Code { get; set; }
        public string Htl_Name { get; set; }
        public string Htl_Description { get; set; }
        public string Htl_Type { get; set; }
        public string Htl_Room_Class { get; set; }
        public string Htl_RoomType { get; set; }
        public Nullable<short> Htl_RoomAcount { get; set; }
        public string Htl_Meals { get; set; }
        public string Train_Station_Code { get; set; }
        public string Train_Station_Name { get; set; }
        public string Train_Station_To_Code { get; set; }
        public string Train_Station_To_Name { get; set; }
        public string Train_Num { get; set; }
        public Nullable<byte> Train_Smoking { get; set; }
        public string Train_Vagon { get; set; }
        public string Train_Site { get; set; }
        public string Train_Class { get; set; }
        public string Train_Ticket { get; set; }
        public System.DateTime DateUpd { get; set; }
        public string UserUpd { get; set; }
        public Nullable<bool> ATC { get; set; }
        public string ESource { get; set; }
        public Nullable<System.DateTime> Airfile_RecordDateCreate { get; set; }
        public Nullable<int> Airfile_FltLine { get; set; }
    }
}
